project_id = "xijfxrfemhdnxwzggpcp"

[functions.finnhub-data]
verify_jwt = false

[functions.institutional]
verify_jwt = false

[functions.news]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = false

[functions.alerts]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.polygon-data]
verify_jwt = false

[functions.quiver-data]
verify_jwt = false

[functions.live-stock-price]
verify_jwt = false

[functions.market-movers]
verify_jwt = false

[functions.ai-trader-pro]
verify_jwt = false

[functions.options-flow]
verify_jwt = false
