// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xijfxrfemhdnxwzggpcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpamZ4cmZlbWhkbnh3emdncGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDE0OTMsImV4cCI6MjA3Mjc3NzQ5M30.pS5eC4dym8RdfqJP-dyFQTdctqgzPbdblqrxcRDAXsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});